# Generated by Django 3.0.2 on 2021-02-03 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='coustomer',
            new_name='Customer',
        ),
    ]
