# Generated by Django 3.1.6 on 2021-02-12 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20210213_0325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='loc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.location'),
        ),
    ]
